name: Atualizacao Automatica da Fila

on:
  workflow_dispatch: # Mantém o botão manual ativado para quando você quiser forçar a atualização
  schedule:
    # Roda no minuto 0 de cada hora, das 10h às 23h e das 00h às 02h (UTC)
    # Isso equivale exatamente das 07:00 às 23:00 no horário de Brasília!
    - cron: '0 0-2,10-23 * * *'
jobs:
  atualizar_fila:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar arquivos do repositorio
        uses: actions/checkout@v3

      - name: Preparar o ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar as ferramentas
        run: |
          pip install gspread pandas numpy

      - name: Rodar o calculo da fila
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python priorizacao.py
